#!/usr/bin/env node
/* =========================================================
   Yummyland — packs the site into a Shopify theme drop-in.

       node tools/build-shopify.js

   Produces shopify/assets/* from the source files:
     - site images are copied flat as yummyland-<path>.<ext>
     - JS is copied under theme-safe names
     - CSS is scoped to .yummyland so it cannot restyle the theme,
       and font URLs become Shopify asset_url calls
     - products.csv is generated from the real catalogue
   Sections/templates in shopify/ are hand-written and left alone.
   ========================================================= */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'shopify', 'assets');
fs.mkdirSync(OUT, { recursive: true });

/* ---------------------------------------------------------------- JS */
const JS = {
  'config.js': 'yummyland-config.js',
  'art.js': 'yummyland-art.js',
  'data.js': 'yummyland-data.js',
  'store.js': 'yummyland-store.js',
  'site.js': 'yummyland-site.js',
  'pages.js': 'yummyland-pages.js',
  'builder.js': 'yummyland-builder.js',
  'analytics.js': 'yummyland-analytics.js',
  'shopify-cart.js': 'yummyland-shopify-cart.js'
};
Object.keys(JS).forEach((src) => {
  let code = fs.readFileSync(path.join(ROOT, 'assets/js', src), 'utf8');

  if (src === 'config.js') {
    const before = code;
    code = code.replace(/YL\.PHOTO_BASE == null \? '[^']*' : YL\.PHOTO_BASE;/,
      "YL.PHOTO_BASE == null ? '' : YL.PHOTO_BASE;   /* Shopify build: CDN photos */");
    if (code === before) throw new Error('config.js: YL.PHOTO_BASE default not found — update this rewrite');
  }

  fs.writeFileSync(path.join(OUT, JS[src]),
    '/* Generated by tools/build-shopify.js from assets/js/' + src + ' — do not edit here. */\n' + code);
  console.log('js       ->', JS[src]);
});

/* ------------------------------------------------------------- fonts */
const FONTS = ['cormorant', 'cormorant-italic', 'greatvibes', 'jost'];
FONTS.forEach((f) => {
  fs.copyFileSync(path.join(ROOT, 'assets/fonts', f + '.woff2'), path.join(OUT, 'yummyland-' + f + '.woff2'));
  console.log('font     -> yummyland-' + f + '.woff2');
});

/* ------------------------------------------------------------ images */
/* Theme assets are one flat folder, so assets/img/lid/birthday-1.webp
   ships as yummyland-lid-birthday-1.webp — the same name YL.img()
   builds at runtime from YL.ASSET_BASE. */
const IMG = path.join(ROOT, 'assets/img');
const flat = (rel) => 'yummyland-' + rel.replace(/\//g, '-');
(function walk(dir) {
  fs.readdirSync(dir).forEach((name) => {
    const full = path.join(dir, name);
    const rel = path.relative(IMG, full).split(path.sep).join('/');
    if (fs.statSync(full).isDirectory()) { if (rel !== 'candy') walk(full); return; }
    if (!/\.(webp|jpg|png|svg)$/.test(name) || /^(og|apple-touch-icon|favicon)/.test(name)) return;
    fs.copyFileSync(full, path.join(OUT, flat(rel)));
    console.log('image    ->', flat(rel));
  });
})(IMG);

/* --------------------------------------------------------------- CSS */
/* Selectors that must stay global: these elements are appended to <body>. */
const GLOBAL = [/^\.toast/, /^@/, /^:root/, /^body\.modal-open/];

function splitRules(css) {
  const out = [];
  let i = 0, buf = '', depth = 0, selector = '';
  while (i < css.length) {
    const ch = css[i];
    if (ch === '{') {
      if (depth === 0) { selector = buf.trim(); buf = ''; } else { buf += ch; }
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) { out.push({ selector, body: buf }); buf = ''; selector = ''; }
      else { buf += ch; }
    } else {
      buf += ch;
    }
    i++;
  }
  if (buf.trim()) out.push({ selector: null, body: buf });
  return out;
}

function scopeSelector(sel) {
  return sel.split(',').map((one) => {
    const s = one.trim();
    if (!s) return s;
    if (s === '*') return '.yummyland *';
    if (s === 'html' || s === 'body') return '.yummyland';
    if (/^(html|body)\b/.test(s)) return s.replace(/^(html|body)\b/, '.yummyland');
    if (s.indexOf('.yummyland') === 0) return s;
    return '.yummyland ' + s;
  }).join(', ');
}

function scopeCss(css) {
  return splitRules(css).map((rule) => {
    if (rule.selector === null) return rule.body;
    const sel = rule.selector;
    if (GLOBAL.some((re) => re.test(sel))) {
      /* at-rules with nested rules (@media, @supports) need recursion */
      if (/^@(media|supports|container)/.test(sel)) {
        return sel + ' {' + scopeCss(rule.body) + '}';
      }
      return sel + ' {' + rule.body + '}';
    }
    return scopeSelector(sel) + ' {' + rule.body + '}';
  }).join('\n');
}

let css = fs.readFileSync(path.join(ROOT, 'assets/css/style.css'), 'utf8');
css = css.replace(/\/\*[\s\S]*?\*\//g, '');      /* comments would confuse the scoper */
css = scopeCss(css).replace(/url\('?\.\.\/fonts\/([a-z0-9-]+)\.woff2'?\)/g,
  (m, f) => "url({{ 'yummyland-" + f + ".woff2' | asset_url }})");

fs.writeFileSync(path.join(OUT, 'yummyland-style.css.liquid'),
  '/* Generated by tools/build-shopify.js from assets/css/style.css — do not edit here. */\n' +
  '/* Every rule is scoped to .yummyland so the theme keeps its own styling. */\n' + css);
console.log('css      -> yummyland-style.css.liquid (scoped to .yummyland)');

/* ---------------------------------------------------------- products */
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(ROOT, 'assets/js/data.js'), 'utf8'), sandbox);
const YL = sandbox.window.YL;

const COLS = ['Handle', 'Title', 'Body (HTML)', 'Vendor', 'Type', 'Tags', 'Published',
  'Option1 Name', 'Option1 Value', 'Variant SKU', 'Variant Grams', 'Variant Inventory Tracker',
  'Variant Inventory Qty', 'Variant Inventory Policy', 'Variant Fulfillment Service',
  'Variant Price', 'Variant Requires Shipping', 'Variant Taxable', 'Status'];

const esc = (v) => {
  const s = String(v == null ? '' : v);
  return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
};
const row = (o) => COLS.map((c) => esc(o[c])).join(',');

const base = {
  Vendor: 'Yummyland', Published: 'TRUE', 'Variant Grams': 0,
  'Variant Inventory Tracker': '', 'Variant Inventory Qty': 0,
  'Variant Inventory Policy': 'continue', 'Variant Fulfillment Service': 'manual',
  'Variant Requires Shipping': 'TRUE', 'Variant Taxable': 'TRUE', Status: 'active',
  'Option1 Name': 'Title', 'Option1 Value': 'Default Title'
};

const rows = [];

/* 1. the gift box — one product, one variant; the order rides on it as
      line item properties */
rows.push(row(Object.assign({}, base, {
  Handle: 'ruby-signature-gift-box',
  Title: YL.BOX.name,
  'Body (HTML)': '<p>A ' + YL.BOX.size + ' rigid gift box with ' + YL.BOX.cups + ' sealed cups of candy you choose ' +
    '(about ' + YL.BOX.cupOz + ' oz each) and a lid printed for the occasion.</p>',
  Type: 'Gift box',
  Tags: 'yummyland, gift-box',
  'Variant SKU': YL.BOX.sku,
  'Variant Grams': Math.round((YL.BOX.cups * YL.BOX.cupOz + 14) * 28.3495),
  'Variant Price': YL.BOX.price.toFixed(2)
})));

/* 2. finishing touches — added as their own lines, grouped to the box */
YL.EXTRAS.forEach((e) => {
  rows.push(row(Object.assign({}, base, {
    Handle: 'yl-' + e.id,
    Title: e.name + ' (gift box add-on)',
    'Body (HTML)': '<p>' + e.desc + '</p>',
    Type: 'Box add-on',
    Tags: 'yummyland, yl-addon',
    'Variant SKU': e.sku,
    'Variant Price': e.price.toFixed(2),
    'Variant Requires Shipping': 'FALSE'
  })));
});

/* 3. refill pouches — ordinary products */
YL.PRODUCTS.forEach((p) => {
  rows.push(row(Object.assign({}, base, {
    Handle: p.id.replace(/^pouch-/, 'refill-pouch-'),
    Title: p.name,
    'Body (HTML)': '<p>' + p.desc + '</p>',
    Type: 'Refill pouch',
    Tags: 'yummyland, yl-addon, refill',
    'Variant SKU': p.sku,
    'Variant Grams': 454,
    'Variant Price': p.price.toFixed(2)
  })));
});

fs.writeFileSync(path.join(ROOT, 'shopify', 'products.csv'), COLS.join(',') + '\n' + rows.join('\n') + '\n');
console.log('products -> shopify/products.csv (' + rows.length + ' rows)');
console.log('\nNext: shopify/README-SHOPIFY.md');
