#!/usr/bin/env node
/* =========================================================
   Yummyland — packs the site into a Shopify theme drop-in.

       node tools/build-shopify.js

   Produces shopify/assets/* from the source files:
     - JS is copied under theme-safe names
     - CSS is scoped to .yummyland so it cannot restyle the theme,
       and font URLs become Shopify asset_url calls
     - products.csv is generated from the real catalogue
   Sections/templates in shopify/ are hand-written and left alone.
   ========================================================= */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'shopify', 'assets');
fs.mkdirSync(OUT, { recursive: true });

/* ---------------------------------------------------------------- JS */
const JS = {
  'config.js': 'yummyland-config.js',
  'art.js': 'yummyland-art.js',
  'data.js': 'yummyland-data.js',
  'store.js': 'yummyland-store.js',
  'site.js': 'yummyland-site.js',
  'pages.js': 'yummyland-pages.js',
  'builder.js': 'yummyland-builder.js',
  'analytics.js': 'yummyland-analytics.js',
  'shopify-cart.js': 'yummyland-shopify-cart.js'
};
Object.keys(JS).forEach((src) => {
  const code = fs.readFileSync(path.join(ROOT, 'assets/js', src), 'utf8');
  fs.writeFileSync(path.join(OUT, JS[src]),
    '/* Generated by tools/build-shopify.js from assets/js/' + src + ' — do not edit here. */\n' + code);
  console.log('js       ->', JS[src]);
});

/* ------------------------------------------------------------- fonts */
['nunito', 'baloo2'].forEach((f) => {
  fs.copyFileSync(path.join(ROOT, 'assets/fonts', f + '.woff2'), path.join(OUT, 'yummyland-' + f + '.woff2'));
  console.log('font     -> yummyland-' + f + '.woff2');
});

/* --------------------------------------------------------------- CSS */
/* Selectors that must stay global: these elements are appended to <body>. */
const GLOBAL = [/^\.toast/, /^@/, /^:root/];

function splitRules(css) {
  const out = [];
  let i = 0, buf = '', depth = 0, selector = '';
  while (i < css.length) {
    const ch = css[i];
    if (ch === '{') {
      if (depth === 0) { selector = buf.trim(); buf = ''; } else { buf += ch; }
      depth++;
    } else if (ch === '}') {
      depth--;
      if (depth === 0) { out.push({ selector, body: buf }); buf = ''; selector = ''; }
      else { buf += ch; }
    } else {
      buf += ch;
    }
    i++;
  }
  if (buf.trim()) out.push({ selector: null, body: buf });
  return out;
}

function scopeSelector(sel) {
  return sel.split(',').map((one) => {
    const s = one.trim();
    if (!s) return s;
    if (s === '*') return '.yummyland *';
    if (s === 'html' || s === 'body') return '.yummyland';
    if (/^(html|body)\b/.test(s)) return s.replace(/^(html|body)\b/, '.yummyland');
    if (s.indexOf('.yummyland') === 0) return s;
    return '.yummyland ' + s;
  }).join(', ');
}

function scopeCss(css) {
  return splitRules(css).map((rule) => {
    if (rule.selector === null) return rule.body;
    const sel = rule.selector;
    if (GLOBAL.some((re) => re.test(sel))) {
      /* at-rules with nested rules (@media, @supports) need recursion */
      if (/^@(media|supports|container)/.test(sel)) {
        return sel + ' {' + scopeCss(rule.body) + '}';
      }
      return sel + ' {' + rule.body + '}';
    }
    return scopeSelector(sel) + ' {' + rule.body + '}';
  }).join('\n');
}

let css = fs.readFileSync(path.join(ROOT, 'assets/css/style.css'), 'utf8');
css = css.replace(/\/\*[\s\S]*?\*\//g, '');      /* comments would confuse the scoper */
css = scopeCss(css)
  .replace(/url\(\.\.\/fonts\/nunito\.woff2\)/g, "url({{ 'yummyland-nunito.woff2' | asset_url }})")
  .replace(/url\(\.\.\/fonts\/baloo2\.woff2\)/g, "url({{ 'yummyland-baloo2.woff2' | asset_url }})");

fs.writeFileSync(path.join(OUT, 'yummyland-style.css.liquid'),
  '/* Generated by tools/build-shopify.js from assets/css/style.css — do not edit here. */\n' +
  '/* Every rule is scoped to .yummyland so the theme keeps its own styling. */\n' + css);
console.log('css      -> yummyland-style.css.liquid (scoped to .yummyland)');

/* ---------------------------------------------------------- products */
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(path.join(ROOT, 'assets/js/data.js'), 'utf8'), sandbox);
const YL = sandbox.window.YL;

const COLS = ['Handle', 'Title', 'Body (HTML)', 'Vendor', 'Type', 'Tags', 'Published',
  'Option1 Name', 'Option1 Value', 'Variant SKU', 'Variant Grams', 'Variant Inventory Tracker',
  'Variant Inventory Qty', 'Variant Inventory Policy', 'Variant Fulfillment Service',
  'Variant Price', 'Variant Requires Shipping', 'Variant Taxable', 'Status'];

const esc = (v) => {
  const s = String(v == null ? '' : v);
  return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
};
const row = (o) => COLS.map((c) => esc(o[c])).join(',');

const base = {
  Vendor: 'Yummyland Candy', Published: 'TRUE', 'Variant Grams': 0,
  'Variant Inventory Tracker': '', 'Variant Inventory Qty': 0,
  'Variant Inventory Policy': 'continue', 'Variant Fulfillment Service': 'manual',
  'Variant Requires Shipping': 'TRUE', 'Variant Taxable': 'TRUE', Status: 'active'
};

const rows = [];

/* 1. the box product — one variant per size */
YL.SIZES.forEach((s, i) => {
  rows.push(row(Object.assign({}, base, {
    Handle: 'build-your-own-candy-box',
    Title: i === 0 ? 'Build Your Own Candy Box' : '',
    'Body (HTML)': i === 0
      ? '<p>Pick your box size, choose your candy, add extras — we pack it fresh and ship it out.</p>'
      : '',
    Type: i === 0 ? 'Candy box' : '',
    Tags: i === 0 ? 'yummyland, box-builder' : '',
    'Option1 Name': 'Size',
    'Option1 Value': s.name + ' — ' + s.serves + ', up to ' + s.slots + ' candies',
    'Variant SKU': 'YL-BOX-' + s.id.toUpperCase(),
    'Variant Price': s.price.toFixed(2)
  })));
});

/* 2. paid extras */
YL.EXTRAS.filter((e) => e.price > 0).forEach((e) => {
  rows.push(row(Object.assign({}, base, {
    Handle: 'yl-extra-' + e.id,
    Title: e.name + ' (box add-on)',
    'Body (HTML)': '<p>' + e.desc + '. Added automatically with a custom box.</p>',
    Type: 'Box add-on',
    Tags: 'yummyland, yl-addon, yl-extra',
    'Option1 Name': 'Title', 'Option1 Value': 'Default Title',
    'Variant SKU': 'YL-EXTRA-' + e.id.toUpperCase(),
    'Variant Price': e.price.toFixed(2),
    'Variant Requires Shipping': 'FALSE'
  })));
});

/* 3. premium candy upcharges */
YL.CANDIES.filter((c) => c.extra > 0).forEach((c) => {
  rows.push(row(Object.assign({}, base, {
    Handle: 'yl-premium-' + c.id,
    Title: c.name + ' (premium candy upgrade)',
    'Body (HTML)': '<p>' + c.flavor + '. Upgrade charge for one premium candy slot.</p>',
    Type: 'Box add-on',
    Tags: 'yummyland, yl-addon, yl-premium',
    'Option1 Name': 'Title', 'Option1 Value': 'Default Title',
    'Variant SKU': 'YL-PREMIUM-' + c.id.toUpperCase(),
    'Variant Price': c.extra.toFixed(2),
    'Variant Requires Shipping': 'FALSE'
  })));
});

fs.writeFileSync(path.join(ROOT, 'shopify', 'products.csv'), COLS.join(',') + '\n' + rows.join('\n') + '\n');
console.log('products -> shopify/products.csv (' + rows.length + ' rows)');
console.log('\nNext: shopify/README-SHOPIFY.md');
