#!/usr/bin/env node
/* =========================================================
   Yummyland — pulls every candy photo out of the Shopify CDN
   and into the repo, so the static site has no external
   dependencies at all.

       node tools/fetch-photos.js            download + wire up
       node tools/fetch-photos.js --check    report, change nothing
       node tools/fetch-photos.js --restore  drop local copies, back to CDN

   What it does:
     - downloads each YL.CANDIES[].img to assets/img/candy/<id>.<ext>
     - lists them in assets/js/photos.js (YL.PHOTOS), which art.js
       prefers over the CDN url
     - leaves data.js alone, so the CDN stays the source of truth and
       the Shopify build keeps using it (see YL.PHOTO_BASE in config.js)

   Candies without an `img` (photo still to be shot) are skipped; the
   site draws them until a photo exists.

   Safe to re-run: files already on disk are skipped, and a candy whose
   download fails simply keeps falling back to the CDN.
   ========================================================= */
'use strict';

const fs = require('fs');
const path = require('path');
const vm = require('vm');
const https = require('https');
const http = require('http');

const ROOT = path.join(__dirname, '..');
const DATA = path.join(ROOT, 'assets/js/data.js');
const DIR = path.join(ROOT, 'assets/img/candy');
const MAP = path.join(ROOT, 'assets/js/photos.js');
const REL = 'assets/img/candy/';

const mode = process.argv.includes('--restore') ? 'restore'
  : process.argv.includes('--check') ? 'check' : 'fetch';

/* ------------------------------------------------------------------ */
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(DATA, 'utf8'), sandbox);
const CANDIES = sandbox.window.YL.CANDIES.filter((c) => c.img);

function writeMap(map) {
  fs.writeFileSync(MAP, '/* Generated by tools/fetch-photos.js — local copies of candy photos,\n' +
    '   candy id -> file in assets/img/candy/. Empty means every photo is\n' +
    '   served from the Shopify CDN. Do not edit by hand. */\n' +
    'window.YL = window.YL || {};\nwindow.YL.PHOTOS = ' + JSON.stringify(map, null, 2) + ';\n');
}

const ext = (url) => {
  const m = url.split('?')[0].match(/\.([a-z0-9]+)$/i);
  return m ? m[1].toLowerCase() : 'jpg';
};
const fileFor = (c) => c.id + '.' + ext(c.img);

/* ------------------------------------------------------------- restore */
if (mode === 'restore') {
  writeMap({});
  if (fs.existsSync(DIR)) fs.rmSync(DIR, { recursive: true });
  console.log('restored — photos.js emptied, ' + REL + ' removed');
  process.exit(0);
}

/* --------------------------------------------------------------- check */
if (mode === 'check') {
  let have = 0;
  CANDIES.forEach((c) => { if (fs.existsSync(path.join(DIR, fileFor(c)))) have++; });
  const wired = (fs.readFileSync(MAP, 'utf8').match(/": "/g) || []).length;
  console.log('candies      ' + CANDIES.length);
  console.log('files on disk ' + have);
  console.log('wired in photos.js ' + wired);
  console.log(have === CANDIES.length && wired === CANDIES.length
    ? 'photos are local — the site has no external dependencies'
    : 'photos still come from cdn.shopify.com at runtime');
  process.exit(0);
}

/* --------------------------------------------------------------- fetch */
/* Shopify's CDN resizes on request; 800px covers a retina candy card
   without hauling down the 2000px original. */
const WIDTH = 800;

function download(url, dest, redirects) {
  return new Promise((resolve, reject) => {
    const get = url.indexOf('http://') === 0 ? http.get : https.get;
    get(url, { headers: { 'user-agent': 'yummyland-build' } }, (res) => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        if ((redirects || 0) > 4) return reject(new Error('too many redirects'));
        return resolve(download(res.headers.location, dest, (redirects || 0) + 1));
      }
      if (res.statusCode !== 200) {
        res.resume();
        return reject(new Error('HTTP ' + res.statusCode));
      }
      const tmp = dest + '.part';
      const out = fs.createWriteStream(tmp);
      res.pipe(out);
      out.on('finish', () => {
        out.close(() => {
          if (fs.statSync(tmp).size < 1024) {
            fs.unlinkSync(tmp);
            return reject(new Error('suspiciously small'));
          }
          fs.renameSync(tmp, dest);
          resolve();
        });
      });
      out.on('error', reject);
    }).on('error', reject);
  });
}

(async () => {
  fs.mkdirSync(DIR, { recursive: true });
  const got = [];
  const failed = [];

  for (const c of CANDIES) {
    const file = fileFor(c);
    const dest = path.join(DIR, file);
    if (fs.existsSync(dest)) { got.push(c); continue; }
    const url = c.img + (c.img.indexOf('?') > -1 ? '&' : '?') + 'width=' + WIDTH;
    try {
      await download(url, dest);
      got.push(c);
      process.stdout.write('.');
    } catch (e) {
      failed.push(c.id + ' (' + e.message + ')');
      process.stdout.write('x');
    }
  }
  process.stdout.write('\n');

  /* list the downloaded ones; the rest stay on the CDN */
  const map = {};
  got.forEach((c) => { map[c.id] = fileFor(c); });
  writeMap(map);
  console.log('downloaded/present ' + got.length + '/' + CANDIES.length + ', wired ' + got.length);
  if (failed.length) {
    console.log('still on the CDN:\n  - ' + failed.join('\n  - '));
  }
  console.log(fs.readdirSync(DIR).length + ' files in ' + REL);
})();
